apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-simple-kubectl-task
spec:
  inputs:
    resources:
    - name: git-source
      type: git
    params:
    - name: version
      type: string
      description: version of the deployment and tag of the image
      default: latest
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
  - name: install-new
    image: lachlanevenson/k8s-kubectl
    script: |
      #!/bin/sh
      sed -i -e 's#$VER#$(inputs.params.version)#g' ./git-source/user-app/config/deploy.yaml
      sed -i -e 's#$IMAGE#$(outputs.resources.builtImage.url)#g' ./git-source/user-app/config/deploy.yaml
      kubectl apply -f ./git-source/user-app/config
