apiVersion: v1
kind: Namespace
metadata:
  name: kabanero
  labels:
    istio-injection: enabled

---

#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: demo-virtual-service
#  namespace: kabanero  
#spec:
#  hosts:
#  - "*"
#  gateways:
#  - demo-gateway
#  http:  
#  - route:
#     - destination:
#        host: demo
#        port:
#          number: 3000
#
---

#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: demo-gateway
#  namespace: kabanero
#spec:
#  selector:
#    istio: ingressgateway # use istio default controller
#  servers:
#  - port:
#      number: 80
#      name: http
#      protocol: HTTP
#    hosts:
#    - "*"
#
---

apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: kabanero
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - port: 3000
    targetPort: 3000



