apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
  - name: version
    type: string
    default: latest
    description: version of the deployment and tag of the image
  - name: project
    type: string
    default: demo
    description: project name
  - name: namespace
    type: string
    default: kabanero
    description: project name
  - name: eventlistener
    type: string
    description: dispatcher event listener name
  - name: configmap-name
    type: string
    description: name configmap
  - name: key-name
    type: string
    description: key name in the data
  - name: repo_full_name
    default: ""
    description: 
  - name: sha
    default: ""
    description:
  - name: request_url
    default: ""
    description:
  resources: 
  - name: git-source
    type: git
  - name: docker-image
    type: image
  workspaces:
  - name: output
  - name: input
  tasks:
  - name: build-simple
    taskRef:
      name: build-push
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: builtImage
        resource: docker-image
  - name: generate-load
    runAfter: [build-simple]
    taskRef:
      name: generate-load-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
    params:
    - name: version
      value: $(params.version)
    - name: target-namespace
      value: $(params.namespace)
  - name: iter8
    runAfter: [build-simple]
    params:
    - name: version
      value: $(params.version)
    - name: project-name
      value: $(params.project)
    - name: target-namespace
      value: $(params.namespace)
    taskRef: 
      name: create-experiment-task
  - name: deploy-simple
    runAfter: [iter8]
    params:
    - name: version
      value: $(params.version)
    taskRef: 
      name: deploy-simple-kubectl-task
    resources: 
      inputs:
      - name: git-source
        resource: git-source 
      outputs:
      - name: builtImage
        resource: docker-image
  - name: wait
    runAfter: [iter8]
    workspaces:
    - name: output
      workspace: output
    params:
    - name: version
      value: $(params.version)
    - name: project-name
      value: $(params.project)
    - name: target-namespace
      value: $(params.namespace)
    - name: configmap-name
      value: $(params.configmap-name)
    - name: key-name
      value: $(params.key-name)
    - name: repo_full_name
      value: $(params.repo_full_name)
    - name: sha
      value: $(params.sha)
    - name: request_url
      value: $(params.request_url)
    taskRef: 
      name: wait-completion-task
  - name: notify
    runAfter: [wait]
    workspaces:
    - name: input
      workspace: input
    params:
    - name: eventlistener
      value: $(params.eventlistener)
    taskRef:
      kind: Task
      name: notify

